# Generated by Django 6.0 on 2025-12-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Pessoa',
        ),
    ]
